### ISSUE TITLE
Documentation of API

### ISSUE THREAD

**Issue by Hanzik** [TarkovTracker/TarkovTracker#104]
It would be nice to have a Swagger documentation (or whatever is popular these days).

**Comment by thaddeus** [comment]
👍
Just going to document what we talked about earlier here as the goals for this (these can be either this issue, or split into multiple)
- [ ] Generate swagger doc from API file (https://www.npmjs.com/package/swagger-jsdoc)
- [ ] Keep swagger doc in GitHub releases (https://github.com/TarkovTracker/TarkovTracker/blob/master/.github/workflows/tag-create-release-draft.yml)
- [ ] Host latest Release's swagger doc in a SwaggerUI (Maybe use the TarkovTracker github page for that? https://github.com/peter-evans/swagger-github-pages)

**Comment by Hanzik** [comment]
Alright, I managed to get most of it working. Live example is here: https://hanzik.github.io/TarkovTracker/ Gotta say, these GitHub pages seem like they can be pretty handy and I would definitely go this route.

1) Generating the SwaggerUI page on the go is poorly documented and seems like it's not worth the trouble. People suggest including the page as-is in the project. I placed all of its files in /docs folder - GitHub likes this folder for their "Pages".

2) Having the SwaggerUI up and available, we now only need to generate the API definition using the swagger-jsdoc. This can be done with 'npm run swagger' from the functions/ folder. This can be in the main package.json instead as I am not sure what the difference between the main one and the one in functions folder is supposed to be, but that's just a detail.

3) I moved the api.js to functions/api/v1 folder. The swagger-jsdoc needs some extra annotations for component definitions which I placed into a separate files to keep the api.js as "short" as possible. Didn't wanna throw everything into the functions folder.

What is left now? 
a) Setup the GitHub Pages in the main project. Settings > Pages > master + /docs. No theme needs to be selected.
b) Unless I misunderstood your second point, it feels to me like there is no need to setup anything in .github/workflows. GitHub pages read directly from the repository /docs folder, so whoever works on API or changes any of the annotations just has to run 'npm run swagger' to update the Swagger definition and push it with rest of the changes within the same commit. It *would* be nice if this was automated, but I don't see any reasonable way how you can force running 'npm run swagger' before 'git commit' :smile:
