### ISSUE TITLE
Wrong map orientation for Customs and Interchange

### ISSUE THREAD

**Issue by Shebuka** [TarkovTracker/TarkovTracker#126]
Hi,
there is an established 'orientation' that most users are used to seeing on other sites (like the official wiki or tools like mapgenie) to orient themselves on all maps. 

Currently on TarkovTracker the:
* Customs map is rotated 180 degrees 🔄 (must be rotated 180 degrees to match wiki https://escapefromtarkov.fandom.com/wiki/Customs_Interactive_Map)
* Interchange map is rotated 90 degrees to the right ⟳ (must be rotated 90 degrees to the left ⟲ to match wiki https://escapefromtarkov.fandom.com/wiki/Interchange?file=InterchangeMap_Updated_4.24.2020.png)

**Comment by Hanzik** [comment]
There was a discussion about this whether we would stick to standards or to cardinal directions and Thaddeus went with the second option. It might take some time getting used to this, but since the addition of compass to the game, having north being "up" on all of the maps is the way to go I feel. But I understand your point... even I am more used to the old orientation, but I think that will soon pass.

**Comment by Shebuka** [comment]
It will be ok if every other map tool is also converted to the cardinal direction or if you are using only TarkovTracker. But currently, it's really difficult to see Interchange in "standard" way for like jackets, caches and other loot locations and then mentally rotate the map to the cardinal direction for quest markers...

**Comment by thaddeus** [comment]
> It will be ok if every other map tool is also converted to the cardinal direction

That's the goal, someone has to be the first person to change (although I'm certain this isn't actually the first), and considering TarkovTracker is fairly widely used, and [offering the maps openly to other tools and individuals to use, with sources](https://github.com/TarkovTracker/tarkovdata/tree/master/maps), hopefully this is a good first step to other things updating to use the new orientation now that we know cardinal directions.

**Comment by thaddeus** [comment]
That being said, I did totally screw up Interchange cardinal north while using the official map to reference, so I will fix that.
