### ISSUE TITLE
Add a numerical progress to the progress charts

### ISSUE THREAD

**Issue by dierke9** [TarkovTracker/TarkovTracker#177]
At the moment you only see the bars at the progress charts. It would be nice to also see it numerical, that way it is more clear to see how many still need to be done.
Example:
![image](https://user-images.githubusercontent.com/3934909/145263002-af9deacd-4ee6-4a72-96e7-7be0b579489f.png)

**Comment by thaddeus** [comment]
@dierke9 Thanks for the feedback - definitely a good idea and will put it in the queue!

**Comment by thaddeus** [comment]
Resolved by @jmozzetta in #197
