### ISSUE TITLE
TypeError: this.$root.levelDataDefault[this.selfLevel] is undefined

### ISSUE THREAD

**Issue by michael-krebs** [TarkovTracker/TarkovTracker#199]
When I loaded into the website the level tracker on the left was at 71. I clicked all the way down to 1 and then clicked down again and it wrapped back to 71. I then clicked up to 75 to try to get back to the start. If I remember correctly it got stuck there and I refreshed the page. The level tracker does not show up anymore. I also get this stack trace (truncated because most of it is minified)

```js
TypeError: this.$root.levelDataDefault[this.selfLevel] is undefined
    levelGroup https://tarkovtracker.io/js/chunk-2d0ddbd4.5c7030d5.js:1
    get https://tarkovtracker.io/js/chunk-vendors.b1f01aaa.js:19
    evaluate https://tarkovtracker.io/js/chunk-vendors.b1f01aaa.js:19
    dr https://tarkovtracker.io/js/chunk-vendors.b1f01aaa.js:19
    groupIcon https://tarkovtracker.io/js/chunk-2d0ddbd4.5c7030d5.js:1
    get https://tarkovtracker.io/js/chunk-vendors.b1f01aaa.js:19
    evaluate https://tarkovtracker.io/js/chunk-vendors.b1f01aaa.js:19
```

edit: My vuex `progress/level` is 71

**Comment by Faalagorn** [comment]
Thanks for reporting this! I reported this issue on Discord as well, here's what I wrote there:

> Oh crap, I tried to fiddle a little with my level indicator and when I got it down from 1 it went to 72. Then I could get to 75 at which point it got stuck and now I don't see it at all. According to the API token imported to tarkov-tools, I am definitely above level 15 since I have access to flea there. Seems like some weird bug there. Can someone take a look at my profile to see how it is now?
> I just tested it now whie logging off and it seems like that:
> 1) you press down arrow from level 1, it goes to level 71
> 2) you press the up arrow to get to level 75 and beyond
> 3) you can't go down or up now, stuck on level 75. It does show the level indicator for me still, though
> Oh and after I clicked up arrow from level 75 and then refreshed page, it doesn't show anymore
> So it seems when you are above level 75 it gets buggy
> Clearing cookies got me back to level 71
> Resetting my progression helped
