### ISSUE TITLE
Needed items quests locked behind level

### ISSUE THREAD

**Issue by Shebuka** [TarkovTracker/TarkovTracker#210]
Currently, in "Needed items" I see two quests (Crisis and Night Sweep) on top of the list that are actually locked far away for me behind my level. Now that we have a player level stored I suggest that these quests will be shown at least after the one you have currently unlocked (that are for both for your level and prerequisite quests) so that the first one you see is the actual stuff you need right now.

**Comment by Truesh00ter** [comment]
@thaddeus this seems to be still going on (see image below)
If implementing the check between the level and quests reqs is too much (I thought it was already implemented?) can we get the option to 'manually lock' quests? I would understand that people see little reason to see a quest that reqs lvl 7 sniper for instance. We all know it's a long way to go, cba to see it every time. Along with locking crisis in below screenshot (wiki: "Must be level 48 to start this quest)". 



![image](https://user-images.githubusercontent.com/17280249/217499651-4a84ab12-9141-4043-a5b4-4bf6621c4779.png)

**Comment by Shebuka** [comment]
_Premisys_: The wiki may not be up to date on this quest and quests.json was sunset in favour of _[tarkov.dev](https://tarkov.dev)_ API query.

If you completed the prerequisite quest **Athlete** then **Crisis** should be available for you. As per our data **Crisis** doesn't have a minimum level requirement and *Athlete** is level 30.

Did you complete **Athlete**? If yes, maybe **Crisis** is timed, can you check after 24 hours if you get access to **Crisis**?

**Comment by Truesh00ter** [comment]
> Did you complete **Athlete**? If yes, maybe **Crisis** is timed, can you check after 24 hours if you get access to **Crisis**?

@Shebuka based on the chat message:

![image](https://user-images.githubusercontent.com/17280249/217516246-347fd7c6-dbac-4ca2-a98e-caa60b95631d.png)

It (**Athlete**) was completed at least 3+ days ago. 

--
My 2cts. From a player perspective, unlocking Crisis which reqs. multiple LEDX FIR having a low lvl req makes no sense. It cleary is an end game (for most if not for 99,99% of the players) quest (late wipe).
The lvl 48 req might not be updated, but it seems reasonable to me.

**Comment by MatthiasHeinz** [comment]
> _Premisys_: The wiki may not be up to date on this quest and quests.json was sunset in favour of _[tarkov.dev](https://tarkov.dev)_ API query.
> 
> If you completed the prerequisite quest **Athlete** then **Crisis** should be available for you. As per our data **Crisis** doesn't have a minimum level requirement and _Athlete_* is level 30.
> 
> Did you complete **Athlete**? If yes, maybe **Crisis** is timed, can you check after 24 hours if you get access to **Crisis**?

So we should redirect the issues of "Crisis" being available at level 30 to tarkov.dev, right?

**Comment by Shebuka** [comment]
@MatthiasHeinz Yes, and it would be helpful if you could report back on what level you'll unlock it.

**Comment by MatthiasHeinz** [comment]
Reporting on the actual level might take a while, as I'm still level 37 and probably won't progress too fast.

**Comment by Shebuka** [comment]
Seems to working correctly now, closing
