### ISSUE TITLE
No option to build christmas tree

### ISSUE THREAD

**Issue by Faalagorn** [TarkovTracker/TarkovTracker#212]
I reported it on Discord, but it seems to be no option to build Christmas tree this wipe, despite it being available this wipe. You can mark the items in "Needed items" section, but can't actually build it. It is important, as without it it won't appear imported with the TarkovTracker API Token in https://tarkov-tools.com/ and you can't see the crafts there.

It would be nice if the christmas ornaments would not appear after the event ends in the "Needed items" section too.

**Comment by Faalagorn** [comment]
With the christmas tree gone, it would be wise to hide ornaments from https://tarkovtracker.io/gather though even if I'm pretty sure there will be wipe before next christmas, I wonder what would happen if theoretically there wouldn't be till the next year; would the tree be built? If so, I'd be wise to keep the data but make it hidden for future where there will be servers without wipes in EfT.

**Comment by thaddeus** [comment]
This should be resolved now, as the hideout modules come from tarkov.dev which updates dynamically when the tree is added and removed, as well as the item requirements to do so.
