### ISSUE TITLE
Wrong colors for Discord and GitHub in 12.12 notice

### ISSUE THREAD

**Issue by Faalagorn** [TarkovTracker/TarkovTracker#215]
Currently, black links are barely visible with dark mode, while white logos are barely visible on light mode, maybe they could be all changed to grey or some background added? Shouldn't be too hard to quickly implement I guess. :)
![screenshot_2022-01-09-155129](https://user-images.githubusercontent.com/4951331/148687576-2ab5dddd-e78c-43bb-8ef7-a99d64f83dc6.png)
![screenshot_2022-01-09-155118](https://user-images.githubusercontent.com/4951331/148687577-5e319224-2707-4973-b79e-5b05ceb9bd78.png)

**Comment by thaddeus** [comment]
Closing this as outdated
