### ISSUE TITLE
incorrect unlock data for new lighthouse quest Long Road

### ISSUE THREAD

**Issue by StoffePro** [TarkovTracker/TarkovTracker#218]
The tracker gives me Long Road even if I haven't done Friend from the west pt 2.

Is this just a matter of importing fresh data from the wiki? In that case I guess this issue is pointless.

If not, there are several other errors with new lighthouse quests. Should I create separate issues for each, or should I amend this to include all I know of?

**Comment by Ryuichiro** [comment]
Would probably be best in one Issue so that whoever updates the dependencies can look at a list.
Just noticed, that the follow-up quest "Missing Cargo" is also not locked behind "Long Road" in the Tracker.

**Comment by thaddeus** [comment]
Closing this as outdated
