### ISSUE TITLE
Add stats card indicating estimated Trader reputation

### ISSUE THREAD

**Issue by thaddeus** [TarkovTracker/TarkovTracker#22]
Add starts card to the dashboard that show what your reputation should be according to quest completion. Loop through all completed quests, loop through their reputation rewards, add them together per trader. Then, offset by user's game edition selected.

**Comment by Hanzik** [comment]
Hi there, couple of questions:

1) Do you want this rendered as a stat-card per trader? Wouldn't that add too many cards to already pretty full dashboard? Or just one card with all traders listed? It would be bigger than the rest, but seems reasonable to put this information all together.

2) How about adding the information about the current trader level? To show the trader's level based on the reputation? I know it isn't the only requirement, but it 

3) Is there any way I can see if logged user has EOD edition? Or do you just want "EOD reputation" added in brackets?

4) I also tried implementing it as a graph. It seems alright, but has another set of issues.
  - What should the range of the graph be? Most traders cap at 0.6-0.75, but you can go much higher. So while setting it to ~0.8 is usefull, at some point those graphs will reach the ceiling and wont render the real value (albeit useless number at that point).

Something like this:
![image](https://user-images.githubusercontent.com/5736517/126043900-8aa23985-f011-4a62-80c2-039b6643435d.png)

**Comment by thaddeus** [comment]
@Hanzik - good questions!

1.  I think I'd personally prefer it to be a stat card per trader, but I get what you're saying about there already being a lot of stat cards. I think there are a lot of less-useful or interesting stat cards there, and that information could either be moved to a graph by stat type, or create a more detailed stats page in the future. Things like Placed Objectives, Pickup Objecties, PMC Eliminations and Scav Eliminations are all things that kind of interest me, and I'm assuming a few others, but they don't need to be on the front page. Potentially you could do a size appropriate view of this information by making them a chip group right below the graphs https://vuetifyjs.com/en/components/chip-groups/ - each trader would have a chip with their estimated loyalty level and estimated reputation. Each chip would be a v-col with a size of 1 or 2 so that on smaller screens the chips would respond and realign as necessary. 
![image](https://user-images.githubusercontent.com/1557581/126045379-9703f83d-667b-4f6d-b3e3-dfe201508d4c.png)

2. Yeah, that's a good plan. There's some data available for that in https://github.com/TarkovTracker/tarkovdata/blob/master/traders.json - you'd just need to insert the file into the vue app (see https://github.com/TarkovTracker/TarkovTracker/blob/master/src/trackerGlobalMixin.js#L3 and https://github.com/TarkovTracker/TarkovTracker/blob/master/src/trackerCommonState.js#L32 for common implementations of that)

3. Not currently, but that's something I've been meaning to add into the Settings page. It would just be a new card with a dropdown to select between the different game editions. It would mean adding a property to the progress store (https://github.com/TarkovTracker/TarkovTracker/blob/master/src/store/modules/progress.js) like level, except it would probably be an enum representation of the game version. For the purpose of this issue, you can assume the majority of the people using the site have EoD, and the game edition stuff can be a separate PR after, unless you felt like you wanted to add it to this.

4. I think a graph is a tricky representation of the reputation. The most important thing is representing milestones, which the graph doesn't make simple. You could in theory have your graph representation with a stacked bar chart, where one bar is stacked with different color (or shades) bars to represent each loyalty level threshold. The range of the graph would need to be whatever the highest required reputation is essentially.

**Comment by thaddeus** [comment]
Resolved in #50
