### ISSUE TITLE
Gather page switches are not switches

### ISSUE THREAD

**Issue by opaldes** [TarkovTracker/TarkovTracker#254]
current state:
Switch is off with the label "Show Obtained"
Obtained Items are visible
Turn switch on -> label switches to "Hide obtained"
Obtained items are invisible

should state:
Switch is off with the label "Hide Obtained"
Obtained Items are visible
Turn switch on
Obtained items are invisible

I try setting up the projekt locally today because it should be an easy fix and create a PR once I get the grasp behind.

**Comment by thaddeus** [comment]
Closing this as outdated
