### ISSUE TITLE
Create hideout module skip to buttons

### ISSUE THREAD

**Issue by thaddeus** [TarkovTracker/TarkovTracker#26]
Originally I left out skip to buttons for hideout modules as its fairly quick to jump through them, but on second thought I should add buttons to the locked page for each locked level of the station that lets you complete it and all prerequisites to allow people to catch up quickly

**Comment by Hanzik** [comment]
How would this work? I click the button "Skip to" on "Locked" page and it builds this hideout upgrade and all of it's requirements (and requirements of those requirements and so on)?

**Comment by thaddeus** [comment]
Yeah, on the locked page there would be a skip to, but also skip to buttons for all of the different levels of that module. So you could go to the locked page and click 'Level 3' on workbench, and it would unlock everything up to and including workbench level 3. The tricky part of this is I feel like it would somewhat tie in with the game edition selection with Stash. 

Part of the tracker is that I want to provide a free API for other tools like Rat Scanner and Tarkov Tools so that people can update their progress in one place and then have that progress utilized with the other tools for convenience. Rat Scanner is already using the v1 of the API (super dumb endpoints that provide just the raw progress data). The problem in my head is EOD gives max level stash, which means that should be marked as complete in your progress so its provided via the API (or not if you have standard and haven't upgraded)

The solution is either:
1) Add some smarts to the API endpoint to automatically go through the progress data when its returned based upon the gameEdition value and virtualize the stash upgrades as complete. In this solution, the tracker would do something similar and just hide the stash upgrades as appropriate. My main concern with this method is I want the logic for this to be unified rather than having it in the functions code https://github.com/TarkovTracker/TarkovTracker/blob/master/functions/api.js and Vuex store https://github.com/TarkovTracker/TarkovTracker/blob/master/src/store/modules/progress.js
2) When you change the game edition, actually mark the appropriate progress ids as complete once and for all. The problem here is going backwards, if you had EoD selected, how do you go back to standard?

If you have any thoughts, they would be appreciated :) Just trying to figure out how to do this 'right'

**Comment by Hanzik** [comment]
1) I haven't really looked much into API part, but it seems like it should read this information from one place, ideally directly from the progress store. 
2) This is tricky indeed. I don't think there is one correct answer. But I suppose changing editions should just change the level of Stash you have and it wouldn't touch any of the "would-be" requirements - as in, it doesn't build them automatically. It also seems like Stash Level 1 should also be built automatically (or Max level Stash if you have EOD edition).

**Comment by thaddeus** [comment]
1. Part of the magic of the tracker is that its using Google Firebase's Firestore. its a NoSQL database which can allow the client to directly connect and control the data with no in between, which means the only cost is data storage, reads and writes - which is why this can be a free service for hundreds of thousands of users. So having an backend that validates and constructs the data isn't ideal. I think the solution is writing a common set of functions that are imported by both the API endpoints and the Web Client's store. I'll try looking at that soon to unblock this aspect of it.

2. That seems like a good way to do it. So it would mark the parent hideout ids as complete, but leave the underlying requirements as uncomplete, then if you rolled your game edition back to standard, it would uncomplete the parent module, and you would just have to click up to the correct version of the stash through the skip buttons (assuming you upgraded it if you actually were on a lower game edition)

The more I think about it, this can probably be implemented as is, and the game edition/stash stuff can be figured out later.

**Comment by Hanzik** [comment]
1) By "service" I meant a common set of functions, just like you said. I think this can do without proper backend just fine.

2) I started implementing this whole thing just to see how it all behaves - when I force building something, it autocompletes all requirements. When I downgrade a hideout module, it downgrades all modules that have this downgraded module as prerequirement. Where Stash is concerned, I feel like an exception should be made to exclude this recursive upgrading/downgrading when user has an EOD edition selected. And when somebody makes a change from EOD to anything else, Stash gets set to Level 1 and we let users click up to the real level of their Stash.

**Comment by thaddeus** [comment]
Awesome, that all sounds great, and the draft PR looks fantastic! Thanks for taking this on!
