### ISSUE TITLE
Create new Quest view page

### ISSUE THREAD

**Issue by thaddeus** [TarkovTracker/TarkovTracker#3]
From feedback, the quest viewing needs to be reworked. Instead of being separated by map and traders there should be one page which has an intuitive interface to switch between those, and all quests, and other filters like 'Epsilon only' and 'Kappa only'.

**Comment by HuskyNator** [comment]
If possible could this contain loyalty and/or player level tracking?
In that way current quests could be tracked in such a way only quests you can currently accept/do could be shown.
