### ISSUE TITLE
Skier's "Safe Corridor" blocked for taking different path, actually not blocked ingame.

### ISSUE THREAD

**Issue by Jadaju** [TarkovTracker/TarkovTracker#312]
I completed Prapor's "Big Customer" and Skier's "Safe Corridor" is blocked for it. It's not blocked ingame though, so you can do this quest even if you didn't complete "Chemical - Part 4".

**Comment by thaddeus** [comment]
Sorry for the extremely late reply - this should be resolved, closing this!
