### ISSUE TITLE
API is broken

### ISSUE THREAD

**Issue by montana123** [TarkovTracker/TarkovTracker#342]
Unfortunately the API is broken check: https://tarkovtracker.io/api/v1/token

Also the swagger api is throwing a cors error: https://tarkovtracker.github.io/TarkovTracker/

EDIT: Wrong URL in swagger

**Comment by zelloxy** [comment]
Which URL should it be?

**Comment by XenSide** [comment]
> Unfortunately the API is broken check: https://tarkovtracker.io/api/v1/token
> 
> Also the swagger api is throwing a cors error: https://tarkovtracker.github.io/TarkovTracker/
> 
> EDIT: Wrong URL in swagger

Didn't a v2 get released? https://tarkovtracker.io/api/v2/token

**Comment by thaddeus** [comment]
Closing this as resolved
