### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by alexjshepler** [TarkovTracker/TarkovTracker#346]
Hi, I'm wanting to help out on this but I'm not sure where, is there a to do list somewhere?

**Comment by thaddeus** [comment]
Sorry for the very late reply - I haven't done a good job of keeping track of issues for this repository. For anyone (yourself or others) interested in helping out, I'm trying to update all of the issues with tags according to whether they are bugs, feature requests, or other. If anyone has questions, feel free to ping me directly on Discord, as that's where I'm most likely to see it in a reasonable amount of time. I'll try to be better about keeping up with issues and comments here, though!
