### ISSUE TITLE
Quest: 'Cease Fire!' req. incorrect

### ISSUE THREAD

**Issue by Truesh00ter** [TarkovTracker/TarkovTracker#349]
Quest: 'Cease Fire!' listed as active/open while wiki states (https://escapefromtarkov.fandom.com/wiki/Cease_Fire!) that this quests requires a previous quest which also is open at the same time.
Fix: make 'Cease Fire!' req. 'The Delicious Sausage'.
I believe the current req. for 'Cease Fire!' on tarkovtracker only is the lvl req. The proof is in the pudding, I have 'The Delicious Sausage' active in-game while 'Cease Fire!' is nowhere to be seen.

![image](https://user-images.githubusercontent.com/17280249/213919135-9fb665bd-6060-457c-8ded-8c1db9a3dc2a.png)

![image](https://user-images.githubusercontent.com/17280249/213919305-ae698bd4-e73e-4516-8109-b4f3f1a5af30.png)

**Comment by PeterNilssonDev** [comment]
Second that. I got the same issue. I see "cease fire" in the tracker, but not in game.

**Comment by Shebuka** [comment]
Reposted in tarkov.dev discord: https://discord.com/channels/956236955815907388/956239773742288896/1074659914292678676

**Comment by Shebuka** [comment]
BTW, this was already fixed 👍

**Comment by Shebuka** [comment]
It was fixed in this commit: https://github.com/the-hideout/tarkov-data-manager/commit/eceade6805bf049c9d166df39df54341d3ecb9ff

Only the developers of this repository or the reporter can close the issues. On our side (tarkov.dev API) we have done everything we can ;)
