### ISSUE TITLE
Quest "Calibration" should require Level 47 instead of Level 22

### ISSUE THREAD

**Issue by SpaghettiProgrammer** [TarkovTracker/TarkovTracker#350]
Current State requiring Level 22:

![image](https://user-images.githubusercontent.com/32932474/215098901-78bc62ca-4d80-4b74-9ef3-4d4195cdf157.png)

Level 47 required per [Wiki](https://escapefromtarkov.fandom.com/wiki/Calibration)

![image](https://user-images.githubusercontent.com/32932474/215098967-4dda6bae-5c8d-409f-9a34-44eaaade7dab.png)

**Comment by Shebuka** [comment]
Reposted in tarkov.dev discord: https://discord.com/channels/956236955815907388/956239773742288896/1074659140275814441

**Comment by Shebuka** [comment]
Fixed in https://github.com/the-hideout/tarkov-data-manager/pull/205 👍

**Comment by thaddeus** [comment]
Closing as resolved
