### ISSUE TITLE
The Delicious Sausage is not shown if filtered on map streets of tarkov

### ISSUE THREAD

**Issue by PeterNilssonDev** [TarkovTracker/TarkovTracker#351]
Without any filter I see "The Delicious Sausage" quest correctly. But if I filter on map streets for tarkov (where all four location you are expected to find is located) I do not see "The Delicious Sausage"

How to reproduce
1. Filter on map street for tarkov
2. Expected: I can see quest "The Delicious Sausage"
3. Actual: I can not see "The Delicious Sausage"

Wiki link: https://escapefromtarkov.fandom.com/wiki/The_Delicious_Sausage

**Comment by thaddeus** [comment]
Closing as resolved
