### ISSUE TITLE
Quest "Friend from the West" should require Level 9 and be available after Quest Supplier

### ISSUE THREAD

**Issue by Zitronensaft** [TarkovTracker/TarkovTracker#353]
Current State:
![image](https://user-images.githubusercontent.com/50299233/216817217-c2171127-35f3-483d-a9ba-0dbbd7d88d3d.png)

Wiki:

![image](https://user-images.githubusercontent.com/50299233/216817242-0d4439b9-2904-4683-828e-3b52dca534f4.png)

![image](https://user-images.githubusercontent.com/50299233/216817253-b2d62c4e-5259-4364-a4f7-f2a972585560.png)

**Comment by Shebuka** [comment]
Wiki is wrong, you are also required to be Loyalty Level 2 with Skier, and LL2 requires you to be level 15. So you can't get the quest unless you are level 15.

**Comment by Zitronensaft** [comment]
![image](https://user-images.githubusercontent.com/50299233/218118155-00ad313c-ba49-435d-8953-7e1cb15a8e6b.png)

**Comment by Shebuka** [comment]
Did they change it again then? I grinded to level 15 and 800k spending to get to LL2 with Skier and get this quest...

**Comment by Shebuka** [comment]
Should be fixed ;)

**Comment by thaddeus** [comment]
Closing as resolved
