### ISSUE TITLE
Appearance/handling of faction specific quests

### ISSUE THREAD

**Issue by MatthiasHeinz** [TarkovTracker/TarkovTracker#357]
It would be great, if there was some indication on the "Tasks"-page, if a quest is faction (Bear/USEC) specific.
E.g.:
- "Green Corridor" by Prapor is Bear only.
- "Our own land" by Prapor is Bear only.
- "Counteraction" by Peacekeeper is USEC only.

Alternatively if one could specify their faction within their "Settings" page, it would be possible to hide the tasks of the other faction entirely or automatically mark them as irrelevant/completed (in case an other team member of the other faction needs to complete them).

**Comment by thaddeus** [comment]
Closing this as resolved - Tasks now show with the Faction icon in their title and on the details sidebar. Tasks for other factions should be hidden by default - but will appear if you are showing teammate's tasks and they have an available task for the opposite faction (that task should still show as unavailable to you). 
![image](https://github.com/TarkovTracker/TarkovTracker/assets/1557581/0dcb9f06-1699-4a20-8574-d229a431b5f3)

Feel free to reopen if you have other suggestions on how you would prefer this displayed!
