### ISSUE TITLE
Updates to quest "Reserve"

### ISSUE THREAD

**Issue by MatthiasHeinz** [TarkovTracker/TarkovTracker#359]
According to the wiki, the quest "Reserve" should be locked behind the quest [The Delicious Sausage](https://escapefromtarkov.fandom.com/wiki/The_Delicious_Sausage).

Additionally the link to the wiki should point to the quest page [Reserve (Quest)](https://escapefromtarkov.fandom.com/wiki/Reserve_(quest)) instead of the page of the location [Reserve](https://escapefromtarkov.fandom.com/wiki/Reserve).

**Comment by Shebuka** [comment]
Reposted in tarkov.dev discord: https://discord.com/channels/956236955815907388/956239773742288896/1074648546764128256

**Comment by MatthiasHeinz** [comment]
Thanks.
