### ISSUE TITLE
Request api speed problem

### ISSUE THREAD

**Issue by inxk233** [TarkovTracker/TarkovTracker#370]
Hello everyone, I would like to ask a little question. I try to deploy TarkovTracker locally, but it takes a long time to get data from the api, almost 30S, but https://tarkovtracker.io/ only needs 1 second to load. That is why ah.

Can I cache the data returned by the request in the web server?

**Comment by thaddeus** [comment]
Sorry for the very late reply to this - this would usually occur if you changed the GraphQL query to tarkov.dev - it wouldn't match the cached result and might have taken much longer to generate a response. If you run into this again in the future, feel free to reopen this and we can discuss!
