### ISSUE TITLE
French language

### ISSUE THREAD

**Issue by nrhome** [TarkovTracker/TarkovTracker#380]
Can you develop the French language with the right names of quests and their tasks, objects and modules of the hideout with those of Tarkov France? Google Translate does not support search fields. Thank you very much in advance.

**Comment by thaddeus** [comment]
Hey! Thanks for opening an issue for this! I would love to add more languages to TarkovTracker - unfortunately I only know English and a little bit of German, so I wouldn't do a very good job translating to French. Luckily, we have a i18n module, and people can submit translations by creating a `fr.json5` file by copying the `en.json5` file and updating each of the translation phrases. If anyone out there is fluent in French and comfortable doing so, I would really appreciate the help! I'm adding a link to the localization files here https://github.com/TarkovTracker/TarkovTracker/tree/master/tarkov-tracker/src/locales
