### ISSUE TITLE
Have the ability to skip quests and hideout upgrades

### ISSUE THREAD

**Issue by nrhome** [TarkovTracker/TarkovTracker#381]
Have the ability to skip (checkbox and uncheck at any time) quests and hideout upgrades, which will update the list of needed items.

**Comment by thaddeus** [comment]
Sorry for the late response - this can be done by showing the "Locked" tabs of both Tasks and Hideout modules, you can jump to or mark complete what you've already done, and quickly update your progress to where you are without going through each task or upgrade one by one.
