### ISSUE TITLE
TarkovTracker not updating automatically after API key has been provided to TarkovMonitor

### ISSUE THREAD

**Issue by Encrux** [TarkovTracker/TarkovTracker#387]
Not sure if this is the correct repo to submit this to.

I followed the installation instructions of TarkovMonitor and provided the API key from TarkovTracker. TarkovMonitor says the token is valid and TarkovTracker doesn't appear to show any error messages. I tried two different tokens, one with get and write progression, and one where I accepted all three settings.

From the described behaviour, I now expect to see my progress being updated on the TarkovTracker website. However, I can still see beginner tasks like Pharmacist that I have to complete manually. 

Is this expected behaviour? Am I missing some kind of setting?

Thank you in advance!

**Comment by thaddeus** [comment]
Hello! Sorry for the delay in responding to this - TarkovMonitor only updates as it reads new logs being written while the monitor is open (to prevent things like logs from previous wipes or other accounts from conflicting). So if you complete a task in game while the monitor is open, it will update that task in TarkovTracker for you via the API. If you have any other issues, feel free to reopen this or open a new issue.
