### ISSUE TITLE
Update player level on API task competions

### ISSUE THREAD

**Issue by thaddeus** [TarkovTracker/TarkovTracker#389]
When a user marks a task as complete via the API, check if the player's current level is below the completed task's minimum - if it is, update it to be the minimum of the completed task. 

Ideally we would be able to get the players actual level out of TarkovMonitor, but currently the only way to do that would be to trust group members who receive the group event logs. 

One other future way we could infer player level is from trader loyalty level minimums from things like hideout upgrades.

**Comment by 0pilatos0** [comment]
Hey @thaddeus , is this issue open for contributions?
