### ISSUE TITLE
Rubbles needed for Loaylty Buyout showing in Needed Items

### ISSUE THREAD

**Issue by Crook3r** [TarkovTracker/TarkovTracker#427]
In Needed Items, rubbles for Loaylty Buyout are showing for me, altough I choosed different path in this quest line. I choosed Chemical - Part 4 in the line, so I am having related quest to this quest. It is showing only in tab Needed Items, in Tasks window, I don't see this quest.

![obrazek](https://github.com/TarkovTracker/TarkovTracker/assets/13300791/ec4906ff-8488-442e-a610-5ab7f8870cdc)
![obrazek](https://github.com/TarkovTracker/TarkovTracker/assets/13300791/aa09f1e1-c791-4652-b236-dceb4a44af2b)

**Comment by r-gruber** [comment]
Go to Tasks->Traders->Skier->Locked, you should see the quest there. You can manually mark it as completed.
The app cannot track these tasks where you have multiple options. So the only thing you'll be able to do right now is to mark the other tasks as completed manually.

**Comment by Crook3r** [comment]
Thanks, got it now correct.
