### ISSUE TITLE
Rewrite filtering and display options for Needed Items

### ISSUE THREAD

**Issue by thaddeus** [TarkovTracker/TarkovTracker#43]
Add new filtering and display options for the needed items page to match the new functionality of the all quests page

**Comment by beuker81** [comment]
May I suggest to add a switch or something that it shows the total items needed for one specific item for all quests and hideout stuff together? 

For example you have quest A and quest C need both USB Sticks. 2 for A and 3 for C. Also for the hideout you need another 5. So when the switch is set you will the the total number of USB sticks you need (10) instead for each quest a different line with USB Sticks and you have to add them up.

So per row the total needed items over all the quests and hideout showing on one line.

**Comment by thaddeus** [comment]
@beuker81 Thanks for the feedback - that's actually already available on the needed items page. In the top right there's a slider to go between details and totals views 
![image](https://user-images.githubusercontent.com/1557581/126016210-463fb0b4-7cd5-4191-b1e8-5007e8380031.png)

**Comment by beuker81** [comment]
@thaddeus Oooh... The label totally send me the wrong way. My guess was that is showed more details and that wasn't what I was looking for. Ok now I understand that the label/text is showing what you actually see instead of what you could see.

Maybe it's something to look at because me and my friends all had the same idea.

Thanks anyway! It's a great website!

**Comment by beuker81** [comment]
I think I found a bug here. Some of the items say 0/0.

Total switch on:
![image](https://user-images.githubusercontent.com/5682660/126032832-51c1c946-3858-465f-a4fe-8832129d4bfa.png)

Total switch off:
![image](https://user-images.githubusercontent.com/5682660/126032860-7e985872-b70a-47aa-99bc-44618e0962af.png)

**Comment by thaddeus** [comment]
Closing this as resolved - there is an issue for a new totals view with the TT redesign
