### ISSUE TITLE
Unable to access TarkovTracker UI due to Group Leader leaving Group

### ISSUE THREAD

**Issue by itsmeopii** [TarkovTracker/TarkovTracker#98]
A group of friends and I decided to create an account/sign in and try the new group feature on the app which allowed us to view each other's Tarkov progression. One member was having problems in viewing the rest of the group's progression. He (the original group creator) decided that he would try to leave said group and re-join. Another group member and I were viewing the group settings when he left the group. After he left, we have been unable to access the app's UI. All pages we try to access on the app result in a completely blank page (all white).

**Comment by thaddeus** [comment]
Hey! Sorry you're having problem - I think I've seen this bug once or twice before but haven't had enough information to nail it down exactly. If you could hop on the project's Discord (https://discord.gg/zeAP4Ng) and send me (Apologist#0007) a DM with the email you used to sign up, I can investigate better. Thanks!

**Comment by thaddeus** [comment]
Closing this as outdated
